services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  api:
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
      - TMDB_API_KEY=${TMDB_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: bash -c "npx drizzle-kit generate && npx drizzle-kit push --force && npm run start"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  pgdata: