openapi: 3.0.0
info:
  title: Letterboxd API
  version: 1.0.0
  description: API documentation for the Letterboxd project

paths:
  /:
    get:
      summary: Returns a welcome message
      responses:
        '200':
          description: Welcome message
  /u/register:
    post:
      summary: Registers a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: success
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      username:
                        type: string
                        example: johndoe
                      role:
                        type: string
                        example: user
                      createdAt:
                        type: string
                        format: date-time
                        example: '2023-10-01T12:00:00Z'
                description: User successfully registered
        '400':
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Username or password missing, or user already exists"
          description: Username or password missing, or user already exists

        '405':
          description: Method Not Allowed
          
        '500':
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Error registering user"
          description: Error registering user

  /u/login:
    post:
      summary: Authenticates a user and returns a JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: User successfully authenticated, returns user details and JWT token
        '400':
          description: Username or password missing
        '401':
          description: Invalid credentials
        '500':
          description: Error logging in

  /u/me:
    get:
      summary: Retrieves the current authenticated user's details
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: Bearer <token>
      responses:
        '200':
          description: Returns the authenticated user's details
        '401':
          description: Not authenticated or invalid/expired token
        '404':
          description: User not found

  /movies:
    get:
      summary: Retrieves a list of movies
      responses:
        '200':
          description: A list of movies
        '500':
          description: Error retrieving movies

    post:
      summary: Adds a new movie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                director:
                  type: string
                releaseYear:
                  type: integer
              required:
                - title
                - director
                - releaseYear
      responses:
        '201':
          description: Movie successfully added
        '400':
          description: Missing required fields
        '500':
          description: Error adding movie

  /movies/{movieId}:
    get:
      summary: Retrieves details of a specific movie
      parameters:
        - name: movieId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Movie details
        '404':
          description: Movie not found
        '500':
          description: Error retrieving movie details

  /friends:
    get:
      summary: Retrieves a list of friends
      responses:
        '200':
          description: A list of friends
        '500':
          description: Error retrieving friends

    post:
      summary: Adds a new friend
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
                - username
      responses:
        '201':
          description: Friend successfully added
        '400':
          description: Missing required fields
        '500':
          description: Error adding friend

  /friends/{friendId}:
    delete:
      summary: Removes a friend
      parameters:
        - name: friendId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Friend successfully removed
        '404':
          description: Friend not found
        '500':
          description: Error removing friend